name: Chip-Level Test
description: Issue to track the development of a chip-level test.
title: "[chip-test] "
labels: ["Component:ChipLevelTest"]
body:
  - type: input
    id: name
    attributes:
      label: Test point name
      description: Test point name with link to entry in test plan.
      placeholder: >
        Example: [chip_sw_uart_tx_rx](https://github.com/lowRISC/opentitan/blob/65e2c995beb96806d13bf04dcd8ef25ca64ac6c5/hw/top_earlgrey/data/chip_testplan.hjson#L24)
    validations:
      required: true
  - type: dropdown
    id: host-side-component
    attributes:
      label: Host side component
      description: Does this test require development of a host side component?
      options:
        - SystemVerilog
        - Rust
        - SystemVerilog+Rust
